TARGET=world.out
OBJ=hello.o main.o
$(TARGET):$(OBJ)
	gcc -o $(TARGET) $(OBJ)

#hello.o:hello.c
#	gcc -c hello.c -o hello.o
#main.o:main.c hello.h
#	gcc -c main.c -o main.o

clean:
	rm -f *.o $(TARGET)



